springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui/index.html
    disable-swagger-default-url: true
    display-request-duration: true
    operations-sorter: method
    doc-expansion: none
    default-expanded: false
    operationsSorter: alpha
    tagsSorter: alpha
  use-fqn: true

components:
  schemas:
    ApiResponseTemplate:
      type: object
      required:
        - message
        - code
      properties:
        message:
          type: string
        code:
          type: integer
          minimum: 100
          maximum: 600

    BasicErrorModel:
      type: object
      required:
        - message
        - code
      properties:
        message:
          type: string
        code:
          type: integer
          minimum: 100
          maximum: 600

    ExtendedErrorModel:
      allOf:
        - $ref: '#/components/schemas/ApiResponseTemplate'
        - type: object
          required:
            - rootCause
          properties:
            rootCause:
              type: string