level-ranges:
  levelRangeList:
    - min: 0.0
      max: 3.0
      probabilities:
        SELECT_WORD: 0.7
        WRITE_WORD: 0.3
        READ_WORD: 0.0
        READ_SENTENCE: 0.0
    - min: 3.0
      max: 9.0
      probabilities:
        SELECT_WORD: 0.1
        WRITE_WORD: 0.6
        READ_WORD: 0.3
        READ_SENTENCE: 0.0
    - min: 9.0
      max: 27.0
      probabilities:
        SELECT_WORD: 0.05
        WRITE_WORD: 0.15
        READ_WORD: 0.5
        READ_SENTENCE: 0.3
    - min: 27.0
      max: 1000.0
      probabilities:
        SELECT_WORD: 0.0
        WRITE_WORD: 0.0
        READ_WORD: 0.0
        READ_SENTENCE: 1.0

basic-test:
  probabilities:
    SELECT_WORD: 0.25
    WRITE_WORD: 0.25
    READ_WORD: 0.25
    READ_SENTENCE: 0.25
